image: node:10

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm install
    - npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker build . -t dmsc/duo-cron-job
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push dmsc/duo-cron-job
  tags:
    - docker
  only:
    - master

