# This is a basic workflow to help you get started with Actions

name: Test && Build && Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [develop, master]

env:
  NODE_VERSION: 16.x

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: cp .env.test .env
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        # Don't login if dependabot is creating the PR
        if: ${{ !startsWith(github.head_ref, 'dependabot') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # For debugging capture the selected branch
      - name: Extracted branch
        run: echo "Extracted branch ${{ github.head_ref }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # Don't push if dependabot is creating the PR
          push: ${{ !startsWith(github.head_ref, 'dependabot') }}
          tags: ghcr.io/userofficeproject/user-office-cron:${{ github.head_ref }}
